/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author microsoft
 */
public class addDrivers extends javax.swing.JFrame {
      PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;

    /**
     * Creates new form addDrivers
     */
    public addDrivers() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        availablity = new javax.swing.JComboBox();
        location = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        aadhar = new javax.swing.JLabel();
        aadharId = new javax.swing.JTextField();
        carType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Drivers");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(208, 28, 177, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 150, 27, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 80, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Car Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 250, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Availablity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 290, 110, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Location");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 350, 100, 17);
        jPanel1.add(name);
        name.setBounds(170, 92, 210, 30);
        jPanel1.add(age);
        age.setBounds(170, 142, 210, 30);

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(gender);
        gender.setBounds(170, 190, 210, 30);

        availablity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        availablity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Not Available" }));
        jPanel1.add(availablity);
        availablity.setBounds(170, 290, 210, 30);
        jPanel1.add(location);
        location.setBounds(170, 340, 210, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 460, 120, 40);

        aadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aadhar.setText("Aadhar Id");
        jPanel1.add(aadhar);
        aadhar.setBounds(20, 390, 120, 30);
        jPanel1.add(aadharId);
        aadharId.setBounds(170, 390, 210, 30);

        carType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toyota Fortuner", "Bugaty", "Murcidies", "Odi", "BMW", "Rolls Royce" }));
        jPanel1.add(carType);
        carType.setBounds(170, 242, 210, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\driver1.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 20, 880, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               
        
        try {
          
            
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            
            String Name=name.getText();
            String Age=age.getText();
            String Gender=gender.getSelectedItem().toString();
          String Car_Type=carType.getSelectedItem().toString();
                     
           String Availablity=availablity.getSelectedItem().toString();
           String Location=location.getText();
           String AadharId=aadharId.getText();
            
                 String query9 = "select Car_Type from add_drivers";
            stmt=conn.prepareStatement(query9);
            
            rs = stmt.executeQuery();
           
            String j;
            int k=0;
            Boolean bl=true;       
            
            
            
            
            
           while(rs.next() && bl!=false)
           {
               
    
                j = rs.getString("Car_Type");
               if(j.equals(Car_Type))
               {
                  
                k=1;
               }
           }
   
             
           if(k==1)
           {
               JOptionPane.showMessageDialog(null,"This Car Type Is Already Exist");}
           else{
           String query3 = "select Aadhar_Id from add_drivers";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            
           
            
             bl=true;            
           while(rs.next() && bl!=false)
           {
               
    
                j = rs.getString("Aadhar_Id");
               if(j.equals(AadharId))
               {
                   JOptionPane.showMessageDialog(null,"This Driver Id Is Already Exist");
                bl=false;  
               }
           }
   
                 if(bl!=false)
           {
      JOptionPane.showMessageDialog(null,"Successfully Added Driver");
      
            String query1="insert into add_drivers values('"+Name+"','"+Age+"','"+Gender+"','"+Car_Type+"','"+Availablity+"','"+Location+"','"+AadharId+"')";
            st=conn.createStatement();
            int i=st.executeUpdate(query1);
            this.setVisible(false);
            
   
           }}
               
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDrivers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadhar;
    private javax.swing.JTextField aadharId;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox availablity;
    private javax.swing.JComboBox carType;
    private javax.swing.JComboBox gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
