/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author microsoft
 */
public class addRoom extends javax.swing.JFrame {
    PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;

    /**
     * Creates new form addRoom
     */
    public addRoom() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rn = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        avl = new javax.swing.JComboBox();
        cln = new javax.swing.JComboBox();
        badType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Rooms");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 116, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Availablity");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 170, 140, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cleaning Status");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 220, 140, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 260, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bad Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 310, 120, 17);

        rn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnActionPerformed(evt);
            }
        });
        jPanel1.add(rn);
        rn.setBounds(190, 110, 260, 22);
        jPanel1.add(price);
        price.setBounds(190, 260, 260, 22);

        avl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        avl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Not Available" }));
        jPanel1.add(avl);
        avl.setBounds(190, 170, 260, 23);

        cln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cleaned", "Durty" }));
        jPanel1.add(cln);
        cln.setBounds(190, 220, 260, 23);

        badType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        badType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Bad", "Double Bad" }));
        jPanel1.add(badType);
        badType.setBounds(190, 310, 260, 23);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 380, 130, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\green bad1.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(500, 0, 720, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        try {
          
            
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            
            String RN=rn.getText();
            String AVL=avl.getSelectedItem().toString();
            String CLN=cln.getSelectedItem().toString();
          String Price=price.getText();
         String BadType=badType.getSelectedItem().toString();
                     
           
            int y=0;
            if(y==0)
            {
                 String query3 = "select Room_Number from add_room";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            
            String j;
            
            Boolean bl=true;            
           while(rs.next() && bl!=false)
           {
               
    
                j = rs.getString("Room_Number");
               if(j.equals(RN))
               {
                   JOptionPane.showMessageDialog(null,"This room no is already exist");
                bl=false;  
               }
           }
   
                 if(bl!=false)
           {
      JOptionPane.showMessageDialog(null,"Successfully Added Room");
            String query1="insert into add_room values('"+RN+"','"+AVL+"','"+CLN+"','"+Price+"','"+BadType+"')";
            st=conn.createStatement();
            int i=st.executeUpdate(query1);
            
   
           }
               }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "this is not present here");
        }   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox avl;
    private javax.swing.JComboBox badType;
    private javax.swing.JComboBox cln;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField rn;
    // End of variables declaration//GEN-END:variables
}
