/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author microsoft
 */
public class chackOut extends javax.swing.JFrame {
     PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;
    /**
     * Creates new form chackOut
     */
    public chackOut() {
        initComponents();
           try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String query3 = "select ID_Number from new_costumer_form";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            while(rs.next())
            {
                String a=rs.getString("ID_Number");
                jb.addItem(a);
            }
            }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                    }
  
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb = new javax.swing.JComboBox();
        room = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        chack = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1410, 490));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Check Out");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 210, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Costumer Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 160, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 210, 170, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Chack Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 340, 180, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 340, 180, 40);

        jPanel1.add(jb);
        jb.setBounds(220, 100, 220, 30);

        room.setEditable(false);
        jPanel1.add(room);
        room.setBounds(220, 202, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 140, 30);

        text1.setEditable(false);
        jPanel1.add(text1);
        text1.setBounds(220, 150, 220, 30);

        chack.setText("Chack");
        chack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chackActionPerformed(evt);
            }
        });
        jPanel1.add(chack);
        chack.setBounds(460, 100, 63, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\chackout.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 20, 620, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new reception().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chackActionPerformed

        
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            String value=jb.getSelectedItem().toString();
             String query3 = "select Name from new_costumer_form where ID_Number='"+value+"' ";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            String value1=null;
            while(rs.next())
            {
             value1=rs.getString("Name");
            }
            text1.setText(value1);
            
            String query2="select Allocated_Room_Number from new_costumer_form where ID_Number='"+value+"'";
               stmt=conn.prepareStatement(query2);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("Allocated_Room_Number");
            }
            room.setText(value1);
        }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                     System.out.println(e);
                    }      // TODO add your handling code here:
        
    }//GEN-LAST:event_chackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(chack.isSelected())
      {
        try{          
        Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String value1=jb.getSelectedItem().toString();
             String query1 = "delete from new_costumer_form where ID_Number='"+value1+"' ";
           
              st = conn.createStatement();
                         int x = st.executeUpdate(query1);
                         JOptionPane.showMessageDialog(null, "Successfully Chacked Out");
                           String dbUR = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbUR);
            String Room=room.getText();
            String query6="update add_room set Availablity='available' where Room_Number='"+Room+"'";
           
              st = conn.createStatement();
 
              int y = st.executeUpdate(query6);
             
                this.setVisible(false);
             
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
          
      }}
      else
      {
              JOptionPane.showMessageDialog(null,"Chack Is Not Selected");
              this.setVisible(true);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chackOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chackOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chackOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chackOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chackOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jb;
    private javax.swing.JTextField room;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
