/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author microsoft
 */
public class newCostumerForm extends javax.swing.JFrame {
     PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;

    /**
     * Creates new form newCostumerForm
     */
    public newCostumerForm() {
        initComponents();
                
            try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String query3 = "select Room_Number from add_room";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            while(rs.next())
            {
                String a=rs.getString("Room_Number");
                allocatedRoomNumber.addItem(a);
            }
            }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                    }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        idNumber = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JComboBox();
        idNum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jb1 = new javax.swing.JRadioButton();
        jb2 = new javax.swing.JRadioButton();
        country = new javax.swing.JTextField();
        allocatedRoomNumber = new javax.swing.JComboBox();
        deposite = new javax.swing.JTextField();
        chackedIn = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idNumber.setBackground(new java.awt.Color(255, 255, 255));
        idNumber.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("New Costumer Form");
        idNumber.add(jLabel1);
        jLabel1.setBounds(140, 10, 440, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        idNumber.add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID Number");
        idNumber.add(jLabel3);
        jLabel3.setBounds(30, 150, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        idNumber.add(jLabel4);
        jLabel4.setBounds(30, 190, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        idNumber.add(jLabel5);
        jLabel5.setBounds(30, 230, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Country");
        idNumber.add(jLabel6);
        jLabel6.setBounds(30, 290, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Allocated Room Number");
        idNumber.add(jLabel7);
        jLabel7.setBounds(30, 340, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Chacked In");
        idNumber.add(jLabel8);
        jLabel8.setBounds(30, 390, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Deposite");
        idNumber.add(jLabel9);
        jLabel9.setBounds(30, 440, 180, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        idNumber.add(jButton1);
        jButton1.setBounds(90, 530, 190, 50);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        idNumber.add(jButton2);
        jButton2.setBounds(330, 530, 190, 50);

        id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adhar Card", "Pen Card", "Pasport", "Driving Lisence" }));
        idNumber.add(id);
        id.setBounds(290, 110, 260, 30);
        idNumber.add(idNum);
        idNum.setBounds(290, 150, 260, 30);
        idNumber.add(name);
        name.setBounds(290, 190, 260, 30);

        buttonGroup1.add(jb1);
        jb1.setText("Male");
        idNumber.add(jb1);
        jb1.setBounds(290, 230, 55, 25);

        buttonGroup1.add(jb2);
        jb2.setText("Femail");
        idNumber.add(jb2);
        jb2.setBounds(410, 230, 67, 25);
        idNumber.add(country);
        country.setBounds(290, 290, 260, 30);

        idNumber.add(allocatedRoomNumber);
        allocatedRoomNumber.setBounds(290, 342, 260, 30);
        idNumber.add(deposite);
        deposite.setBounds(290, 440, 260, 30);

        chackedIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        idNumber.add(chackedIn);
        chackedIn.setBounds(290, 392, 260, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\costumers.jpg")); // NOI18N
        idNumber.add(jLabel10);
        jLabel10.setBounds(570, 20, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new reception().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
          
            
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            
            String Id=id.getSelectedItem().toString();
            String IdNumber=idNum.getText();
            String Name=name.getText();
            String Gender=null;
            if(jb1.isSelected())
            {
            Gender="Male";
            }
            else
            {
            if(jb2.isSelected())
            {
            Gender="Femail";
            }
            else
            {
                        JOptionPane.showMessageDialog(null, "Gender Is Not Selected");
            }
       
            }
            String Country=country.getText();
          String Allocated=allocatedRoomNumber.getSelectedItem().toString();
         String ChackedIn=chackedIn.getSelectedItem().toString();
         String Deposite=deposite.getText();
                     
           
            int y=0;
            if(y==0)
            {
                 String query3 = "select ID_Number from new_costumer_form";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            
            String j;
            
            Boolean bl=true;            
           while(rs.next() && bl!=false)
           {
               
    
                j = rs.getString("ID_Number");
                
              
               if(j.equals(IdNumber))
               {
                   JOptionPane.showMessageDialog(null,"This Id Number is already exist");
                bl=false;  
               }
              
           }
           
           
           
           
                 String qu = "select Allocated_Room_Number from new_costumer_form";
            stmt=conn.prepareStatement(qu);
            
            rs = stmt.executeQuery();
                   boolean b2=true;
           while(rs.next() && b2!=false)
           {
              
    
               
                j=rs.getString("Allocated_Room_Number");
               if(j.equals(Allocated))
               {
                   JOptionPane.showMessageDialog(null,"This Room Number is already Occupied");
                b2=false;
               }
              
           }
           
           
   
                 if(bl!=false && b2!=false)
           {
      JOptionPane.showMessageDialog(null,"Successfully Added Costumer");
            String query1="insert into new_costumer_form values('"+Id+"','"+IdNumber+"','"+Name+"','"+Gender+"','"+Country+"','"+Allocated+"','"+ChackedIn+"','"+Deposite+"')";
            st=conn.createStatement();
            int i=st.executeUpdate(query1);
           
                String s="update add_room set availablity='occupied' where Room_Number='"+Allocated+"' ";
                st=conn.createStatement();
                 i=st.executeUpdate(s);
            
   
           }
               }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newCostumerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newCostumerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newCostumerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCostumerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newCostumerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox allocatedRoomNumber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox chackedIn;
    private javax.swing.JTextField country;
    private javax.swing.JTextField deposite;
    private javax.swing.JComboBox id;
    private javax.swing.JTextField idNum;
    private javax.swing.JPanel idNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jb1;
    private javax.swing.JRadioButton jb2;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
