/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author microsoft
 */
public class remove_employ extends javax.swing.JFrame {
 PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;
    /**
     * Creates new form remove_employ
     */
    public remove_employ() {
        initComponents();
          try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String query3 = "select AADHAR from add_employ";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            while(rs.next())
            {
                String l=rs.getString("AADHAR");
                h.addItem(l);
            }
            }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                    }
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        h = new javax.swing.JComboBox();
        i = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chack = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 550));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employ Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Employ Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 180, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Remove Employ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 0, 320, 50);

        jPanel1.add(h);
        h.setBounds(230, 80, 220, 30);

        i.setEditable(false);
        jPanel1.add(i);
        i.setBounds(230, 140, 260, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Job Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 150, 30);

        j.setEditable(false);
        jPanel1.add(j);
        j.setBounds(230, 192, 260, 30);
        jPanel1.add(filler1);
        filler1.setBounds(1080, 510, 0, 0);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 320, 120, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 320, 130, 40);

        chack.setText("Chack");
        chack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chackActionPerformed(evt);
            }
        });
        jPanel1.add(chack);
        chack.setBounds(480, 80, 63, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Employ Gmail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 180, 30);

        k.setEditable(false);
        jPanel1.add(k);
        k.setBounds(230, 240, 260, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\remove_employ.png")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(570, 10, 600, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chackActionPerformed
        // TODO add your handling code here:
   
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            String value=h.getSelectedItem().toString();
             String query3 = "select Name from add_employ where AADHAR='"+value+"' ";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            String value1=null;
            while(rs.next())
            {
             value1=rs.getString("Name");
            }
            i.setText(value1);
            
            String query2="select JOB from add_employ where AADHAR='"+value+"'";
               stmt=conn.prepareStatement(query2);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("JOB");
            }
            j.setText(value1);
            String query7="select EMAIL from add_employ where AADHAR='"+value+"'";
               stmt=conn.prepareStatement(query7);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("EMAIL");
            }
            k.setText(value1);
        }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                     System.out.println(e);
                    }      // TODO add your handling code here:
              
        
    }//GEN-LAST:event_chackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             new reception().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if(chack.isSelected())
      {
        try{          
        Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String value1=h.getSelectedItem().toString();
             String query1 = "delete from add_employ where AADHAR='"+value1+"' ";
           
              st = conn.createStatement();
                         int x = st.executeUpdate(query1);
                         JOptionPane.showMessageDialog(null, "Successfully Removed Employ");
                        
             
                this.setVisible(false);
             
          
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
          
      }}
      else
      {
              JOptionPane.showMessageDialog(null,"Chack Is Not Selected");
              this.setVisible(true);
      }
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(remove_employ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(remove_employ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(remove_employ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(remove_employ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new remove_employ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chack;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox h;
    private javax.swing.JTextField i;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField k;
    // End of variables declaration//GEN-END:variables
}
