/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author microsoft
 */
public class updateChackStatus extends javax.swing.JFrame {
     PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;
    /**
     * Creates new form updateChackStatus
     */
    public updateChackStatus() {
        initComponents(); 
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String query3 = "select ID_Number from new_costumer_form";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            while(rs.next())
            {
                String a=rs.getString("ID_Number");
                id.addItem(a);
            }
            }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                    }
  
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox();
        roomNumber = new javax.swing.JTextField();
        costumerName = new javax.swing.JTextField();
        chackedIn = new javax.swing.JTextField();
        ammountPaid = new javax.swing.JTextField();
        pendingAmmount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomStatus = new javax.swing.JTextField();
        chack = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1410, 590));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Costumer Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 230, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Chacked In");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 280, 170, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ammount Paid");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Pending Ammount");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 400, 190, 40);

        jPanel1.add(id);
        id.setBounds(250, 80, 260, 30);

        roomNumber.setEditable(false);
        jPanel1.add(roomNumber);
        roomNumber.setBounds(250, 130, 260, 30);

        costumerName.setEditable(false);
        jPanel1.add(costumerName);
        costumerName.setBounds(250, 230, 260, 30);

        chackedIn.setEditable(false);
        jPanel1.add(chackedIn);
        chackedIn.setBounds(250, 290, 260, 30);
        jPanel1.add(ammountPaid);
        ammountPaid.setBounds(250, 340, 260, 30);

        pendingAmmount.setEditable(false);
        jPanel1.add(pendingAmmount);
        pendingAmmount.setBounds(250, 400, 260, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(140, 510, 170, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 510, 170, 50);

        jPanel2.setBackground(new java.awt.Color(255, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Chack Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(536, 536, 536)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1410, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Room Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 180, 120, 30);

        roomStatus.setEditable(false);
        jPanel1.add(roomStatus);
        roomStatus.setBounds(250, 180, 260, 30);

        chack.setText("Chack");
        chack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chackActionPerformed(evt);
            }
        });
        jPanel1.add(chack);
        chack.setBounds(540, 80, 63, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\chack out3.jpg")); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 110, 820, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new reception().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        
      if(chack.isSelected())
      {
          try {
          
            
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            
          String Id=id.getSelectedItem().toString();
            String RoomNumber=roomNumber.getText();
           String RoomStatus=roomStatus.getText();
         String CostumerName=costumerName.getText();
        String ChackedIn=chackedIn.getText();
                     
           String AmmountPaid=ammountPaid.getText();
            String PendingAmmount=pendingAmmount.getText();
           
            
  
                 
      

                    
            String query1="update new_costumer_form set Allocated_Room_Number='"+RoomNumber+"',Name='"+CostumerName+"',Chacked_In='"+ChackedIn+"',Deposite='"+AmmountPaid+"' where ID_Number='"+Id+"'";
           
              st = conn.createStatement();
 
              
             
            
            int i=st.executeUpdate(query1);
            this.setVisible(false);
            
   
           
                        JOptionPane.showMessageDialog(null, "sucessfully updated account");
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } }
      else
      {
                  JOptionPane.showMessageDialog(null, "Chack Is Not Selected");      
      }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void chackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chackActionPerformed
        // TODO add your handling code here:
        if(chack.isSelected())
        {
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            String value=id.getSelectedItem().toString();
             String query3 = "select Name from new_costumer_form where ID_Number='"+value+"' ";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            String value1=null;
            while(rs.next())
            {
             value1=rs.getString("Name");
            }
            costumerName.setText(value1);
            
            String query2="select Allocated_Room_Number from new_costumer_form where ID_Number='"+value+"'";
               stmt=conn.prepareStatement(query2);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("Allocated_Room_Number");
            }
            String st=value1;
            roomNumber.setText(value1);
            String query4="select Chacked_In from new_costumer_form where ID_Number='"+value+"'";
               stmt=conn.prepareStatement(query4);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("Chacked_In");
            }
            chackedIn.setText(value1);
            String query5="select Deposite from new_costumer_form where ID_Number='"+value+"'";
               stmt=conn.prepareStatement(query5);
            
            rs = stmt.executeQuery();
            
            while(rs.next())
            {
             value1=rs.getString("Deposite");
            }
            ammountPaid.setText(value1);
        String sgl=null;
           String squ="select Bad_Type from add_room where Room_Number='"+st+"'";
            stmt =conn.prepareStatement(squ);
            rs=stmt.executeQuery();
            while(rs.next())
            {
                sgl=rs.getString("Bad_Type");
            }
            roomStatus.setText(sgl);
            String query10="select Price from add_room where Room_Number='"+st+"'";
            
            stmt=conn.prepareStatement(query10);
           
            rs = stmt.executeQuery();
           
            String s = null;
            while(rs.next())
            {
                    
           
             s=rs.getString("Price");
            }       
           
            String i=null;
           
            i =ammountPaid.getText();
           
                int dbam=Integer.parseInt(i);//convert String into integer
           
                int am=Integer.parseInt(s);
                               
                if(dbam<=am)
                {  
                am=am-dbam;
   
                String sg=String.valueOf(am);//convert integer into string
   
                pendingAmmount.setText(sg);
                   
                }
                else
                {   
                    am=dbam-am;
                       
                    String sm=String.valueOf(am);
                       
                     JOptionPane.showMessageDialog(null, "The Costumer Paid "+sm+" Rupess Extra");
                        pendingAmmount.setText("-"+sm+"");
               
                }
                    
                    
            
            
        }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                     System.out.println(e);}}
        else
        {
                        JOptionPane.showMessageDialog(null, "Chack Is Not Selected");
        }
    }//GEN-LAST:event_chackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateChackStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateChackStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateChackStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateChackStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateChackStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ammountPaid;
    private javax.swing.JCheckBox chack;
    private javax.swing.JTextField chackedIn;
    private javax.swing.JTextField costumerName;
    private javax.swing.JComboBox id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pendingAmmount;
    private javax.swing.JTextField roomNumber;
    private javax.swing.JTextField roomStatus;
    // End of variables declaration//GEN-END:variables
}
