/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author microsoft
 */
public class updateRoomStatus extends javax.swing.JFrame {
    PreparedStatement stmt = null;
        Connection conn = null;
        ResultSet rs=null;
        Statement st=null;
 
    /**
     * Creates new form updateRoomStatus
     */
    public updateRoomStatus() {
        initComponents();
         
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
             String query3 = "select ID_Number from new_costumer_form";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            while(rs.next())
            {
                String a=rs.getString("ID_Number");
                jb.addItem(a);
            }
            }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                    }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        room = new javax.swing.JTextField();
        availablity = new javax.swing.JTextField();
        clean = new javax.swing.JComboBox();
        jb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        chack = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1390, 720));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 450, 190, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Room Status");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 330, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Gest Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 160, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Availablity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 220, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Clean Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 280, 130, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 450, 170, 50);

        room.setEditable(false);
        jPanel1.add(room);
        room.setBounds(200, 160, 250, 30);

        availablity.setEditable(false);
        jPanel1.add(availablity);
        availablity.setBounds(200, 220, 250, 30);

        clean.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cleaned", "Durty" }));
        jPanel1.add(clean);
        clean.setBounds(200, 280, 250, 30);

        jPanel1.add(jb);
        jb.setBounds(200, 90, 250, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\microsoft\\Pictures\\same size hotel management photo\\White Bad1.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(570, 10, 820, 530);

        chack.setText("Chack");
        chack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chackActionPerformed(evt);
            }
        });
        jPanel1.add(chack);
        chack.setBounds(470, 90, 80, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new reception().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(chack.isSelected()){
        try{    // TODO add your handling code here:
         Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
           String value1=room.getText();
         String string=clean.getSelectedItem().toString();
            String val="update add_room set Cleaning_Status='"+string+"' where Room_Number='"+value1+"'";
                         st = conn.createStatement();
 
              int y = st.executeUpdate(val);
 
            
            JOptionPane.showMessageDialog(null, "Sucessfully Update Room Status");
            this.setVisible(false);
    }
    catch(Exception e)
    {JOptionPane.showMessageDialog(null,"Something Went Wrong");
    }
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Chack Is Not Selected");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chackActionPerformed
        // TODO add your handling code here:
            try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            
            String dbURL = "jdbc:mysql://localhost:3308/hotel_management?user=root&password";
            conn = DriverManager.getConnection(dbURL);
            String value=jb.getSelectedItem().toString();
             String query3 = "select Allocated_Room_Number from new_costumer_form where ID_Number='"+value+"' ";
            stmt=conn.prepareStatement(query3);
            
            rs = stmt.executeQuery();
            String value1=null;
            while(rs.next())
            {
             value1=rs.getString("Allocated_Room_Number");
            }
           room.setText(value1);
            
            String query2="yes";
            availablity.setText(query2);
           
           
        }
            catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(null, "Something Went Wrong");
                     System.out.println(e);
                    }
    }//GEN-LAST:event_chackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateRoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateRoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateRoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateRoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateRoomStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availablity;
    private javax.swing.JCheckBox chack;
    private javax.swing.JComboBox clean;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jb;
    private javax.swing.JTextField room;
    // End of variables declaration//GEN-END:variables
}
